In [1]:
import torch

In [2]:
implicit_grads_A = torch.load('./model/implicit_grads_A.pt')
implicit_grads_A[0]

[tensor([ 4.2045e-06, -4.1257e-05,  1.7027e-05,  ..., -1.3981e-05,
          9.7512e-06,  1.2250e-05], device='cuda:0')]

In [2]:
from transformers import MBartTokenizer, MBartForConditionalGeneration
from utils import *

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-en-ro")
tokenizer = MBartTokenizer.from_pretrained("facebook/mbart-large-en-ro")

example_english_phrase = "42 is the answer"
inputs = tokenizer(example_english_phrase, return_tensors="pt")

# Translate
generated_ids = model.generate(inputs["input_ids"], num_beams=4, max_length=5)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

'42 este răspuns'

In [3]:
print(count_parameters_in_MB(model))

610.85184


In [4]:
model.cuda()

MBartForConditionalGeneration(
  (model): MBartModel(
    (shared): Embedding(250027, 1024, padding_idx=1)
    (encoder): MBartEncoder(
      (embed_tokens): Embedding(250027, 1024, padding_idx=1)
      (embed_positions): MBartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0): MBartEncoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerN

In [6]:
import torch

In [7]:
a = torch.rand((3,4))
a

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])

In [8]:
exp_avg_sq = torch.rand((3,4))
exp_avg_sq

tensor([[0.5510, 0.6767, 0.0399, 0.2417],
        [0.0238, 0.1091, 0.8367, 0.7749],
        [0.5436, 0.3681, 0.9233, 0.1707]])

In [10]:
def _concat(xs):
    return torch.cat([x.view(-1) for x in xs])

bias_correction2 = 1 - 0.9 ** 27  
bias_correction2

0.94185026299696

In [15]:
g = a
print(g)
print(exp_avg_sq)
v = exp_avg_sq.mul_(0.9) + (g*g).mul_(1-0.9)
print(exp_avg_sq.mul_(0.9))
print((g*g))
print(v)
v_hat = torch.div(v,bias_correction2)
print(torch.div(v,bias_correction2))

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2635, 0.3237, 0.0191, 0.1156],
        [0.0114, 0.0522, 0.4002, 0.3706],
        [0.2600, 0.1761, 0.4416, 0.0816]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])
tensor([[0.4421, 0.3264, 0.6884, 0.1547],
        [0.0173, 0.0216, 0.1148, 0.1266],
        [0.0040, 0.0753, 0.0011, 0.5030]])
tensor([[0.2814, 0.3239, 0.0860, 0.1195],
        [0.0120, 0.0491, 0.3716, 0.3462],
        [0.2344, 0.1660, 0.3976, 0.1238]])
tensor([[0.2988, 0.3439, 0.0914, 0.1269],
        [0.0127, 0.0522, 0.3946, 0.3676],
        [0.2489, 0.1762, 0.4221, 0.1314]])


In [17]:
print(a)
print(exp_avg_sq)
torch.div(a,exp_avg_sq)

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])


tensor([[ 3.1150,  2.1790, 53.6101,  4.2011],
        [14.2602,  3.4769,  1.0452,  1.1850],
        [ 0.3000,  1.9239,  0.0913, 10.7272]])

In [18]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('t5-small')
def d(l):
    return tokenizer.batch_decode(l,skip_special_tokens=True)
def en(l):
    return tokenizer.tokenize(l,tokenizer,512,True)


In [22]:
d([[    3, 26114,  9458,     6,     3,   362,  2701,  2587,   218,  1197,
           389, 12458,  1818,     3, 23020,     5,     1,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])

['Vielen Dank, ich bin Ihnen für Ihre Anmerkungen danken.']

In [23]:
d([[ 1674, 26114,  9458,     6,     3,   362,  2701,  2587, 12957,  1197,
         25363, 12458,  1818, 12957, 23020,     7,     1,     1,  1674,     1,
             1,     3,  1674,  1674,  1674,     0,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,  1674,  1674,     3,  1674,  1674,  1674,
          1674,  1674,     0,  1674,  1674,  1674,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,     3,  1674]])

['IchVielen Dank, ich bin Ihnen dank Ihre Beiträgemerkungen dankdankens Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich']

In [25]:
import torch

In [33]:
inputid = torch.load('inputid.pt')
targetid = torch.load('targetid.pt')
ori_targetid = torch.load('ori_targetid.pt')
loss_ = torch.load('loss_.pt')
logits = torch.load('logits.pt')
loss = torch.load('loss.pt')

In [37]:
torch.max(logits,-1)

torch.return_types.max(
values=tensor([[ -4.4037,  -4.5025,  -4.9281,  -4.2313,  -5.6924,  -5.6256,  -6.6425,
          -7.2847,  -8.2274,  -7.3021, -10.3613,  -6.9760,  -9.5849,  -6.7073,
          -4.7968,  -8.3601,  -7.5728,  -4.4902,  -5.7067,  -6.7216,  -5.1204,
          -7.6065, -11.9276,  -9.3172,  -5.4782,  -6.3678,  -7.0590,  -9.1610,
          -8.1476,  -7.5388,  -6.8034,  -3.8615,  -7.2199,  -7.4266,  -7.5518,
         -10.1443,  -8.1409, -12.0605,  -9.0083,  -8.2199,  -8.7742,  -7.7515],
        [ -2.5265,  -4.4373,  -5.1066,  -6.1424,  -4.3800,  -3.0445,  -5.1055,
          -3.8776,  -5.8554,  -6.0115,  -5.6690,  -6.0465,  -5.6487,  -5.3771,
          -5.7804,  -3.7082,  -7.5405,  -3.6258,  -5.4839,  -8.9505,  -6.6489,
          -4.6972,  -7.4823,  -6.6585,  -5.3578,  -6.7647,  -6.7611,  -5.0293,
          -4.8628,  -4.6597,  -4.5809,  -4.5091,  -4.4023,  -4.3459,  -4.3446,
          -4.2624,  -4.2697,  -4.1981,  -4.1885,  -4.2973,  -4.2191,  -4.1182]],
       device='cud

In [38]:
d([[12043,    74,    74, 12043,    74,    74,    15, 13568,    64,    74,
            64,    64,    64,  6455,  6455,    15,     6,     6,     6,    67,
            67,  1793,  1793,    74,    74,   961, 11013,  1967,    35,    35,
            74,  6901,  9376, 15656, 13616,    15,    15,    15,    15,    15,
             5,     1],
        [ 1122,     3,    15,     3,   501,   501,   401,  1309,   501,    15,
          2819,    15,     5,    15,   501,   501, 21523, 21523, 21523, 23664,
             5,     5,     5,     1,     1,     3,     3,    15,    15,    15,
            15,    15,    15,    15,    15,    15,    15,    15,    15,    15,
            15,    15]])

['Initiative der der Initiative der dereIndustrie und der und und und Rat Rate,,, die die Ko Ko der der Ge Rechtsvorenen der Energiekennzeichnung insgesamteeeee.',
 'Es e  als als oder link alserechte.e als als Laut Laut LautDisp...  eeeeeeeeeeeeeee']

In [27]:
torch.argmax(targetid,-1)*att

tensor([[ 2167, 12043,     6,    67,   193,    74,     3, 13568,     6,    74,
          5837,  5451,    64,   340,  6455,  8138, 29723,  1177,     6,  6368,
            67,  1793, 10926, 20276,    74,  3988, 11013,  1967,  9146,    35,
           881,  6901,  9376, 15656, 13616,    36,    15, 20322, 16580,    35,
             5,     1],
        [ 1122,   675,     3,    15, 20449,   501,  1309,    49,   401,     3,
          2819,    15, 15192,    15,  1885,   501,  3705,  7775,    18, 23664,
          5595, 24673,     5,     1,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')

In [28]:
ori_targetid

tensor([[ 2167, 12043,     6,    67,   193,    74,     3, 13568,     6,    74,
          5837,  5451,    64,   340,  6455,  8138, 29723,  1177,     6,  6368,
            67,  1793, 10926, 20276,    74,  3988, 11013,  1967,  9146,    35,
           881,  6901,  9376, 15656, 13616,    36,    15, 20322, 16580,    35,
             5,     1],
        [ 1122,   675,     3,    15, 20449,   501,  1309,    15,   401,     3,
          2819,    15, 15192,    15,  1885,   501,  3705,  7775,    18, 23664,
          5595, 24673,     5,     1,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')

In [29]:
inputid

tensor([[13959,  1566,    12,  2968,    10,   100,  6121,     6,  8560,    57,
           681,     6,     8,  3527,    11,     8,  2063,     6,   133,  4840,
          2256,     8,   576,   760,  1433,    13,     8,   126,   827,  3783,
           697,  6704,    38,     3,     9,   829,     5,     1,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [13959,  1566,    12,  2968,    10,    94,    54,  1716,    38,   893,
             3,     9,   646,    42,   269,  3393,     6,    38,   168,    38,
             3,     9, 14227,  5873,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0

In [30]:
from utils import *

In [31]:
d(inputid)

['translate English to German: This initiative, opposed by industry, the Commission and the Council, would impair the coherence of the new energy labelling legislation as a whole.',
 'translate English to German: It can serve as either a left or right monitor, as well as a surround speaker.']

In [32]:
d(ori_targetid)

['Diese Initiative, die von der Industrie, der Kommission und dem Rat abgelehnt wurde, würde die Kohärenz der neuen Rechtsvorschriften zur Energiekennzeichnung insgesamt beeinträchtigen.',
 'Es kann entweder als linke oder rechte Monitore sowie als Surround-Display dienen.']

In [41]:
torch.hstack((torch.ones(3),torch.ones(2)))

tensor([1., 1., 1., 1., 1.])

In [44]:
a= torch.rand((3,2,6))
a

tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895]]])

In [46]:
import os
os.getcwd() 
# os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
import warnings
warnings.filterwarnings("ignore")
from T5 import *
import torch
from datasets import load_dataset,load_metric
from transformers import T5Tokenizer
import torch_optimizer as optim
from transformers.optimization import Adafactor, AdafactorSchedule
from MT_hyperparams import seed_,max_length,target_language
import torch.backends.cudnn as cudnn
from utils import *
from attention_params import *
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler, SubsetRandomSampler
from torch.autograd import Variable
from losses import *
from architect import *
import logging
import sys
import transformers
import time
import argparse
from tqdm import tqdm
import string
pretrained  =  T5ForConditionalGeneration.from_pretrained('t5-small')

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [49]:
pretrained.eval

<bound method Module.eval of T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)

In [54]:

pretrained.apply(turnon_dropout)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro