In [ ]:
facebook/mbart-large-cc25

In [2]:
from transformers import MBartTokenizer, MBartForConditionalGeneration
from utils import *

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-en-ro")
tokenizer = MBartTokenizer.from_pretrained("facebook/mbart-large-en-ro")

example_english_phrase = "42 is the answer"
inputs = tokenizer(example_english_phrase, return_tensors="pt")

# Translate
generated_ids = model.generate(inputs["input_ids"], num_beams=4, max_length=5)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

'42 este răspuns'

In [3]:
print(count_parameters_in_MB(model))

610.85184


In [4]:
model.cuda()

MBartForConditionalGeneration(
  (model): MBartModel(
    (shared): Embedding(250027, 1024, padding_idx=1)
    (encoder): MBartEncoder(
      (embed_tokens): Embedding(250027, 1024, padding_idx=1)
      (embed_positions): MBartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0): MBartEncoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerN

In [6]:
import torch

In [7]:
a = torch.rand((3,4))
a

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])

In [8]:
exp_avg_sq = torch.rand((3,4))
exp_avg_sq

tensor([[0.5510, 0.6767, 0.0399, 0.2417],
        [0.0238, 0.1091, 0.8367, 0.7749],
        [0.5436, 0.3681, 0.9233, 0.1707]])

In [10]:
def _concat(xs):
    return torch.cat([x.view(-1) for x in xs])

bias_correction2 = 1 - 0.9 ** 27  
bias_correction2

0.94185026299696

In [15]:
g = a
print(g)
print(exp_avg_sq)
v = exp_avg_sq.mul_(0.9) + (g*g).mul_(1-0.9)
print(exp_avg_sq.mul_(0.9))
print((g*g))
print(v)
v_hat = torch.div(v,bias_correction2)
print(torch.div(v,bias_correction2))

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2635, 0.3237, 0.0191, 0.1156],
        [0.0114, 0.0522, 0.4002, 0.3706],
        [0.2600, 0.1761, 0.4416, 0.0816]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])
tensor([[0.4421, 0.3264, 0.6884, 0.1547],
        [0.0173, 0.0216, 0.1148, 0.1266],
        [0.0040, 0.0753, 0.0011, 0.5030]])
tensor([[0.2814, 0.3239, 0.0860, 0.1195],
        [0.0120, 0.0491, 0.3716, 0.3462],
        [0.2344, 0.1660, 0.3976, 0.1238]])
tensor([[0.2988, 0.3439, 0.0914, 0.1269],
        [0.0127, 0.0522, 0.3946, 0.3676],
        [0.2489, 0.1762, 0.4221, 0.1314]])


In [17]:
print(a)
print(exp_avg_sq)
torch.div(a,exp_avg_sq)

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])


tensor([[ 3.1150,  2.1790, 53.6101,  4.2011],
        [14.2602,  3.4769,  1.0452,  1.1850],
        [ 0.3000,  1.9239,  0.0913, 10.7272]])

In [18]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('t5-small')
def d(l):
    return tokenizer.batch_decode(l,skip_special_tokens=True)
def en(l):
    return tokenizer.tokenize(l,tokenizer,512,True)


In [22]:
d([[    3, 26114,  9458,     6,     3,   362,  2701,  2587,   218,  1197,
           389, 12458,  1818,     3, 23020,     5,     1,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])

['Vielen Dank, ich bin Ihnen für Ihre Anmerkungen danken.']

In [23]:
d([[ 1674, 26114,  9458,     6,     3,   362,  2701,  2587, 12957,  1197,
         25363, 12458,  1818, 12957, 23020,     7,     1,     1,  1674,     1,
             1,     3,  1674,  1674,  1674,     0,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,  1674,  1674,     3,  1674,  1674,  1674,
          1674,  1674,     0,  1674,  1674,  1674,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,     3,  1674]])

['IchVielen Dank, ich bin Ihnen dank Ihre Beiträgemerkungen dankdankens Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich']

In [1]:
import torch

In [2]:
inputid = torch.load('inputid.pt')
targetid = torch.load('targetid.pt')
ori_targetid = torch.load('ori_targetid.pt')
targetid = torch.load('targetid.pt')

In [3]:
inputid

tensor([[13959,  1566,    12,  2968,    10,   506,  8981,  5608,    13,   633,
           712,  3379,     5,     1,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [13959,  1566,    12,  2968,    10,    27,   183,   182,  2390,    81,
            48,    11,  2396,    82,   676,    11,  7216,    11,  2279,    12,
           320,   114,    79,   130,     3, 23505,   227,   984,     5,     1,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0

In [4]:
torch.argmax(targetid,-1)

tensor([[ 2167,   679, 10377,    35, 17394,   403,  7461,    29, 10072,  4524,
          9977,    35,     5,     1,     1,   316,   316,   316,   316,     3,
             3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
             3,     3,     3,     3],
        [ 1674,  2701,  1319, 31084,    64,     3,  5600,    88,     3,    15,
             7,   426,     6,   602,  3494,   749,   235, 11292,   109,    64,
         15379,    35,    64, 19146,    15,   559,   177, 25711,     7,    35,
           403,  7783,     5,     1]], device='cuda:0')

In [5]:
from utils import *

In [6]:
d([[ 2167,   679, 10377,    35, 17394,   403,  7461,    29, 10072,  4524,
          9977,    35,     5,     1,     1,   316,   316,   316,   316,     3,
             3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
             3,     3,     3,     3],
        [ 1674,  2701,  1319, 31084,    64,     3,  5600,    88,     3,    15,
             7,   426,     6,   602,  3494,   749,   235, 11292,   109,    64,
         15379,    35,    64, 19146,    15,   559,   177, 25711,     7,    35,
           403,  7783,     5,     1]])

['Diese Sektoren bestehen aus mehreren Einzelkomponenten. Die Die Die Die               ',
 'Ich bin sehr britisch und ziehe es vor, dass meine Protokolle und Antworten und Berichte nach den Ereignissen aussehen.']