In [37]:
import torch
x = torch.load('./model/grad.pt')
print(x)

x = torch.load('./model/grad2.pt')
x

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.4999, 0.1712, 0.3778, 0.1286, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000], device='cuda:0'),)

In [21]:
x[0]

tensor([ 2742, 14258,    35,   311,  7716,  1403,  6975,   404,     6,   730,
          558,   211,   749,    17, 12948,   195,     3,  6975, 20415, 20755,
            5,     1,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0], device='cuda:0')

In [2]:
from transformers import MBartTokenizer, MBartForConditionalGeneration
from utils import *

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-en-ro")
tokenizer = MBartTokenizer.from_pretrained("facebook/mbart-large-en-ro")

example_english_phrase = "42 is the answer"
inputs = tokenizer(example_english_phrase, return_tensors="pt")

# Translate
generated_ids = model.generate(inputs["input_ids"], num_beams=4, max_length=5)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

'42 este răspuns'

In [3]:
print(count_parameters_in_MB(model))

610.85184


In [4]:
model.cuda()

MBartForConditionalGeneration(
  (model): MBartModel(
    (shared): Embedding(250027, 1024, padding_idx=1)
    (encoder): MBartEncoder(
      (embed_tokens): Embedding(250027, 1024, padding_idx=1)
      (embed_positions): MBartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0): MBartEncoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerN

In [1]:
import torch

In [3]:
logit = torch.load('logits.pt')

In [4]:
torch.max(logit,-1)

torch.return_types.max(
values=tensor([[8.0154, 8.3163, 6.8179, 7.8733, 7.4541, 6.7119, 7.1219, 6.8108, 8.2726,
         7.2565, 8.5487, 5.9807, 6.1589, 5.5905, 4.9677, 4.7016, 5.3876, 5.8983,
         6.4767, 6.0450, 5.4954, 5.3371, 5.9685, 5.1525, 5.8479, 5.6296, 4.9187,
         6.9132, 5.3252, 6.6821, 5.6075, 6.9862, 7.4293, 5.6309, 6.4429, 5.4112,
         5.8369, 5.0749, 4.7506, 6.0281, 5.3027, 5.7787, 5.7773, 5.0318, 7.0061,
         5.3527, 5.5624, 5.0516, 5.5463, 4.7176, 6.0380, 5.7966, 6.2376, 5.6191,
         5.6257, 5.9693, 5.2556, 6.0416, 5.2538, 6.2667, 5.8113, 5.7909, 5.4132,
         5.9527],
        [8.8492, 5.1780, 5.7451, 7.5030, 5.5787, 5.1651, 6.6790, 5.8783, 5.2510,
         5.9533, 7.2851, 5.3293, 6.4654, 5.7787, 6.9827, 6.3577, 6.3224, 5.6176,
         7.1051, 6.8763, 8.4873, 7.3283, 4.8871, 5.0309, 6.5962, 6.4976, 7.3806,
         8.2380, 5.2951, 5.7772, 7.4459, 5.6607, 6.0298, 6.6780, 7.4407, 6.7936,
         6.2897, 7.2435, 5.3265, 5.4640, 6.5877, 7.7708, 6.6

In [12]:
from utils import *
d([[   41, 24860,    74,   221,   425,     7, 11216,  4267,  4267,     1,
          4267,  9242,    15,    15, 20048,    15, 20048, 20048,     3, 20048,
            15, 20048,     6,   311,     5,     7,    35, 20048, 20048, 20048,
         20048, 20048, 20048, 20048, 20048,    15,   311,    67,    15,    15,
            15,    15,     3,    15, 20048,     5,    15, 28683,    35,     3,
            15, 20048, 20048,   311,   311,     3,     3,    15,   457, 20048,
            15,     3,    15,     5],
        [ 7672, 10206,     3,     1,   425,     1,     1,     3,     1,     3,
         11030,    15, 11621,  5702,  7756,  3019,     3,  5702,     3,     3,
           221,     1,   425,     7,     3,    15, 11030,     7,     3,    67,
             6,    15,     5,     3,     1,     5,     7,     6,     3,    15,
             5, 11878,    15,    15,     5,    67,     3,     7,   218,     3,
             3,     3,     3,     3,     7,  9242, 10808,     1,     3,    15,
             7,    15,   425,  1559],
        [ 2739, 13636,     3, 13636, 10478,     3,     3, 11726, 11726,  7465,
          7465,   329,     3,    35,  7465,   329,   860, 28775,  7793,     3,
            96,     3,  7732,    96,  5823, 11806,  2978, 11726,     3,   860,
          2978,  7217,  7732,    36,     3,     3,  2552,  2978,     3,  7732,
            35,  2406,     3,     3,    35,  8112,  5423,    36,  5423,  2552,
             3,  7217,  2552,    15,     3,     1,   177, 22554,     3,   329,
            15,  8112,    35,  2978],
        [   41, 13636, 10808,    74,    32,   292,   645,   457, 19107,  9242,
           781,  7832,    15,  9408,   425,   425,     7,    32,    32,    32,
           425,    32,     7,  9408, 13657,     6,     3,     3,     6, 13657,
            15,    35,    35,    15,    35,     6,    15,    35, 13657, 13657,
            15, 13657,     6,    35,    35,    35,  4736, 28683,    15,    15,
             3,     6,    15,     6,    15,    15,    15,     6,    15,     6,
            73,    15, 13657,   219]])

['(aufnahme derdeungs Sitzperiperiperi Jahresee Strafe Straf Straf  Strafe Straf, nicht.sen Straf Straf Straf Straf Straf Straf Straf Strafe nicht dieeeee e Straf.e Gonzen e Straf Straf nicht nicht  eez Strafe e.',
 'Frauatte ung   17.ewechselbro Gutauf bro  deungs e 17.s  die,e..s, e. schöneee. die s für     s Jahres werde eseungchen',
 'Wie Parlament  Parlament konnten   Bürger BürgerfürfürM enfürMschherstellerBu  "  einge " NaturMitgliedlichen Bürger schlichen Doch einge be  iumlichen  eingeenck  entreten fest be festium  Dochiume  denstaat Metretenenlichen',
 '( Parlament werde dero Sie einerezsprache Jahres Verlaufenächstenungungsoooungosnächsten Tagen, , Tageneeneneen,een Tagen Tagene Tagen,enenen sei Gonzee,e,eee,e, une Tagen auf']

In [8]:
A  = torch.load('./model/A.pt')
attn_idx  = torch.load('./model/attn_idx.pt')
input_w_attn = torch.load('./model/input_w_attn.pt')
output_w  = torch.load('./model/output_w.pt')
output_w_attn  = torch.load('./model/output_w_attn.pt')
input_w  = torch.load('./model/input_w.pt')

In [18]:
attn_idx

tensor([28, 29, 30, 31], device='cuda:0')

In [10]:
d(input_w)

['translate English to German: That is why my Group firmly rejects the proposal made by the Socialist Group.',
 'translate English to German: (Applause from the PPE-DE Group)',
 'translate English to German: I propose that we vote on the request of the Group of the Party of European Socialists that the Commission statement on its strategic objectives should be reinstated.',
 'translate English to German: (Parliament rejected the request) President.']

In [17]:
d(logits)

NameError: name 'logits' is not defined

In [10]:
def _concat(xs):
    return torch.cat([x.view(-1) for x in xs])

bias_correction2 = 1 - 0.9 ** 27  
bias_correction2

0.94185026299696

In [15]:
g = a
print(g)
print(exp_avg_sq)
v = exp_avg_sq.mul_(0.9) + (g*g).mul_(1-0.9)
print(exp_avg_sq.mul_(0.9))
print((g*g))
print(v)
v_hat = torch.div(v,bias_correction2)
print(torch.div(v,bias_correction2))

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2635, 0.3237, 0.0191, 0.1156],
        [0.0114, 0.0522, 0.4002, 0.3706],
        [0.2600, 0.1761, 0.4416, 0.0816]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])
tensor([[0.4421, 0.3264, 0.6884, 0.1547],
        [0.0173, 0.0216, 0.1148, 0.1266],
        [0.0040, 0.0753, 0.0011, 0.5030]])
tensor([[0.2814, 0.3239, 0.0860, 0.1195],
        [0.0120, 0.0491, 0.3716, 0.3462],
        [0.2344, 0.1660, 0.3976, 0.1238]])
tensor([[0.2988, 0.3439, 0.0914, 0.1269],
        [0.0127, 0.0522, 0.3946, 0.3676],
        [0.2489, 0.1762, 0.4221, 0.1314]])


In [17]:
print(a)
print(exp_avg_sq)
torch.div(a,exp_avg_sq)

tensor([[0.6649, 0.5713, 0.8297, 0.3933],
        [0.1317, 0.1470, 0.3388, 0.3558],
        [0.0632, 0.2744, 0.0327, 0.7092]])
tensor([[0.2135, 0.2622, 0.0155, 0.0936],
        [0.0092, 0.0423, 0.3241, 0.3002],
        [0.2106, 0.1426, 0.3577, 0.0661]])


tensor([[ 3.1150,  2.1790, 53.6101,  4.2011],
        [14.2602,  3.4769,  1.0452,  1.1850],
        [ 0.3000,  1.9239,  0.0913, 10.7272]])

In [18]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('t5-small')
def d(l):
    return tokenizer.batch_decode(l,skip_special_tokens=True)
def en(l):
    return tokenizer.tokenize(l,tokenizer,512,True)


In [22]:
d([[    3, 26114,  9458,     6,     3,   362,  2701,  2587,   218,  1197,
           389, 12458,  1818,     3, 23020,     5,     1,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])

['Vielen Dank, ich bin Ihnen für Ihre Anmerkungen danken.']

In [23]:
d([[ 1674, 26114,  9458,     6,     3,   362,  2701,  2587, 12957,  1197,
         25363, 12458,  1818, 12957, 23020,     7,     1,     1,  1674,     1,
             1,     3,  1674,  1674,  1674,     0,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,  1674,  1674,     3,  1674,  1674,  1674,
          1674,  1674,     0,  1674,  1674,  1674,  1674,  1674,  1674,  1674,
          1674,  1674,  1674,  1674,     3,  1674]])

['IchVielen Dank, ich bin Ihnen dank Ihre Beiträgemerkungen dankdankens Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich Ich  Ich']

In [25]:
import torch

In [33]:
inputid = torch.load('inputid.pt')
targetid = torch.load('targetid.pt')
ori_targetid = torch.load('ori_targetid.pt')
loss_ = torch.load('loss_.pt')
logits = torch.load('logits.pt')
loss = torch.load('loss.pt')

In [37]:
torch.max(logits,-1)

torch.return_types.max(
values=tensor([[ -4.4037,  -4.5025,  -4.9281,  -4.2313,  -5.6924,  -5.6256,  -6.6425,
          -7.2847,  -8.2274,  -7.3021, -10.3613,  -6.9760,  -9.5849,  -6.7073,
          -4.7968,  -8.3601,  -7.5728,  -4.4902,  -5.7067,  -6.7216,  -5.1204,
          -7.6065, -11.9276,  -9.3172,  -5.4782,  -6.3678,  -7.0590,  -9.1610,
          -8.1476,  -7.5388,  -6.8034,  -3.8615,  -7.2199,  -7.4266,  -7.5518,
         -10.1443,  -8.1409, -12.0605,  -9.0083,  -8.2199,  -8.7742,  -7.7515],
        [ -2.5265,  -4.4373,  -5.1066,  -6.1424,  -4.3800,  -3.0445,  -5.1055,
          -3.8776,  -5.8554,  -6.0115,  -5.6690,  -6.0465,  -5.6487,  -5.3771,
          -5.7804,  -3.7082,  -7.5405,  -3.6258,  -5.4839,  -8.9505,  -6.6489,
          -4.6972,  -7.4823,  -6.6585,  -5.3578,  -6.7647,  -6.7611,  -5.0293,
          -4.8628,  -4.6597,  -4.5809,  -4.5091,  -4.4023,  -4.3459,  -4.3446,
          -4.2624,  -4.2697,  -4.1981,  -4.1885,  -4.2973,  -4.2191,  -4.1182]],
       device='cud

In [38]:
d([[12043,    74,    74, 12043,    74,    74,    15, 13568,    64,    74,
            64,    64,    64,  6455,  6455,    15,     6,     6,     6,    67,
            67,  1793,  1793,    74,    74,   961, 11013,  1967,    35,    35,
            74,  6901,  9376, 15656, 13616,    15,    15,    15,    15,    15,
             5,     1],
        [ 1122,     3,    15,     3,   501,   501,   401,  1309,   501,    15,
          2819,    15,     5,    15,   501,   501, 21523, 21523, 21523, 23664,
             5,     5,     5,     1,     1,     3,     3,    15,    15,    15,
            15,    15,    15,    15,    15,    15,    15,    15,    15,    15,
            15,    15]])

['Initiative der der Initiative der dereIndustrie und der und und und Rat Rate,,, die die Ko Ko der der Ge Rechtsvorenen der Energiekennzeichnung insgesamteeeee.',
 'Es e  als als oder link alserechte.e als als Laut Laut LautDisp...  eeeeeeeeeeeeeee']

In [27]:
torch.argmax(targetid,-1)*att

tensor([[ 2167, 12043,     6,    67,   193,    74,     3, 13568,     6,    74,
          5837,  5451,    64,   340,  6455,  8138, 29723,  1177,     6,  6368,
            67,  1793, 10926, 20276,    74,  3988, 11013,  1967,  9146,    35,
           881,  6901,  9376, 15656, 13616,    36,    15, 20322, 16580,    35,
             5,     1],
        [ 1122,   675,     3,    15, 20449,   501,  1309,    49,   401,     3,
          2819,    15, 15192,    15,  1885,   501,  3705,  7775,    18, 23664,
          5595, 24673,     5,     1,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')

In [28]:
ori_targetid

tensor([[ 2167, 12043,     6,    67,   193,    74,     3, 13568,     6,    74,
          5837,  5451,    64,   340,  6455,  8138, 29723,  1177,     6,  6368,
            67,  1793, 10926, 20276,    74,  3988, 11013,  1967,  9146,    35,
           881,  6901,  9376, 15656, 13616,    36,    15, 20322, 16580,    35,
             5,     1],
        [ 1122,   675,     3,    15, 20449,   501,  1309,    15,   401,     3,
          2819,    15, 15192,    15,  1885,   501,  3705,  7775,    18, 23664,
          5595, 24673,     5,     1,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')

In [29]:
inputid

tensor([[13959,  1566,    12,  2968,    10,   100,  6121,     6,  8560,    57,
           681,     6,     8,  3527,    11,     8,  2063,     6,   133,  4840,
          2256,     8,   576,   760,  1433,    13,     8,   126,   827,  3783,
           697,  6704,    38,     3,     9,   829,     5,     1,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [13959,  1566,    12,  2968,    10,    94,    54,  1716,    38,   893,
             3,     9,   646,    42,   269,  3393,     6,    38,   168,    38,
             3,     9, 14227,  5873,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0

In [30]:
from utils import *

In [31]:
d(inputid)

['translate English to German: This initiative, opposed by industry, the Commission and the Council, would impair the coherence of the new energy labelling legislation as a whole.',
 'translate English to German: It can serve as either a left or right monitor, as well as a surround speaker.']

In [32]:
d(ori_targetid)

['Diese Initiative, die von der Industrie, der Kommission und dem Rat abgelehnt wurde, würde die Kohärenz der neuen Rechtsvorschriften zur Energiekennzeichnung insgesamt beeinträchtigen.',
 'Es kann entweder als linke oder rechte Monitore sowie als Surround-Display dienen.']

In [41]:
torch.hstack((torch.ones(3),torch.ones(2)))

tensor([1., 1., 1., 1., 1.])

In [44]:
a= torch.rand((3,2,6))
a

tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895]]])

In [46]:
import os
os.getcwd() 
# os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
import warnings
warnings.filterwarnings("ignore")
from T5 import *
import torch
from datasets import load_dataset,load_metric
from transformers import T5Tokenizer
import torch_optimizer as optim
from transformers.optimization import Adafactor, AdafactorSchedule
from MT_hyperparams import seed_,max_length,target_language
import torch.backends.cudnn as cudnn
from utils import *
from attention_params import *
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler, SubsetRandomSampler
from torch.autograd import Variable
from losses import *
from architect import *
import logging
import sys
import transformers
import time
import argparse
from tqdm import tqdm
import string
pretrained  =  T5ForConditionalGeneration.from_pretrained('t5-small')

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [49]:
pretrained.eval

<bound method Module.eval of T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)

In [54]:

pretrained.apply(turnon_dropout)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro